routes/index.py
from flask import Blueprint, render_template

blueprint = Blueprint('index', __name__)


@blueprint.route('/')
def index():
    return render_template('base.jinja')

routes/memories.py
import markdown
import os
from flask import abort, Blueprint, Markup, redirect, render_template, request, url_for
from utils.calendar import get_calendar_data, NotValidDateError, validate_date
from utils.files import MemoryFile

blueprint = Blueprint('memories', __name__)


@blueprint.route('/memories/<int:year>/')
@blueprint.route('/memories/<int:year>/<int:month>/')
def calendar(year, month=1):
    try:
        validate_date(year, month)
    except NotValidDateError:
        abort(404)

    month_label, month_list, month_file_list = get_calendar_data(year, month)
    return render_template(
        'memories/calendar.jinja',
        year=year,
        month=month,
        month_label=month_label,
        month_list=month_list,
        month_file_list=month_file_list,
    )


@blueprint.route('/memories/calendar/', methods=['POST'])
def calendar_go():
    form_data = request.form
    year = form_data.get('year')
    month = form_data.get('month')
    return redirect(url_for('memories.calendar', year=year, month=month))


@blueprint.route('/memories/<int:year>/<int:month>/<int:day>/')
def memory(year, month, day):
    content = MemoryFile(year, month, day).get_content()
    content = Markup(markdown.markdown(content))
    return render_template(
        'memories/day.jinja',
        year=year,
        month=month,
        day=day,
        content=content,
    )


@blueprint.route('/memories/<int:year>/<int:month>/<int:day>/edit/')
def edit(year, month, day):
    raw_content = MemoryFile(year, month, day).get_preview_content()
    content = Markup(markdown.markdown(raw_content))
    return render_template(
        'memories/edit.jinja',
        year=year,
        month=month,
        day=day,
        raw_content=raw_content,
        content=content,
    )


@blueprint.route('/memories/<int:year>/<int:month>/<int:day>/edit/', methods=['POST'])
def edit_post(year, month, day):
    content = request.form.get('content', '')
    MemoryFile(year, month, day).write_preview(content)
    return redirect(url_for('memories.edit', year=year, month=month, day=day))


@blueprint.route('/memories/<int:year>/<int:month>/<int:day>/save/', methods=['POST'])
def save(year, month, day):
    MemoryFile(year, month, day).save_preview()
    return redirect(url_for('memories.memory', year=year, month=month, day=day))

templates/base.jinja
<html>
<head>
    <title>My Memories</title>
    <style type="text/css">
        html,
        body{
            margin: 0;
            height: 100%;
            font-family: arial, sans-serif;
            text-align: justify;
        }
        a,
        a:hover,
        a:focus,
        a:visited {
            color: #6C71C4;
            text-decoration: none;
        }
        ul {
            padding: 0;
            margin: 0;
        }
        li {
            list-style: none;
        }
        h1 {
            font-size: 24px;
        }
        h2 {
            font-size: 16px;
            font-weight: bold;
        }
        p {
            font-size: 14px;
            line-height: 150%;
        }
        img {
            width: 200px;
        }
        header {
            background-color: #ACA79A;
            height: 40px;
            line-height: 40px;
            text-align: center;
        }
        main {
            display: flex;
            flex-wrap: nowrap;
            min-height: calc(100% - 40px);
        }
        #sidebar {
            background-color: #EBEDEF;
            flex: 0 0 200px;
        }
        .nav-link {
            padding: 5px 10px;
        }
        .nav-link:hover {
            background-color: #C7CBD1;
        }
        .nav-link a {
            display: block;
            width: 100%;
        }
        #content {
            background-color: #FDF6E3;
            flex: 1;
            padding: 20px;
        }
        #content a:hover {
            background-color: #F2ECD9;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body id="{% block body_id %}{% endblock %}">
    <header>
        <a class="navbar-brand" href="{{ url_for('index.index') }}">My Memories</a>
    </header>
    <main>
        <nav id="sidebar" class="bg-light">
            <ul class="left-nav">
                <li class="nav-link"><a href="{{ url_for('memories.calendar', year=2014) }}">2014年</a></li>
                <li class="nav-link"><a href="{{ url_for('memories.calendar', year=2015) }}">2015年</a></li>
                <li class="nav-link"><a href="{{ url_for('memories.calendar', year=2016) }}">2016年</a></li>
                <li class="nav-link"><a href="{{ url_for('memories.calendar', year=2017) }}">2017年</a></li>
            </ul>
        </nav>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </main>
    {% block additional_js %}{% endblock %}
</body>
</html>

templates/memories/calendar.jinja
{% extends "base.jinja" %}

{% block css %}
<style>
    .calendar {
        width: 80%;
        margin: 0 auto;
        min-height: 650px;
        text-align: center;
    }
    .calendar .title {
        font-size: 24px;
        margin-bottom: 10px;
    }
    .calendar .header,
    .calendar .row {
        border-bottom: grey 1px solid;
        display: flex;
        flex-wrap: nowrap;
    }
    .calendar .header {
        font-size: 18px;
    }
    .calendar .row {
        font-size: 16px;
    }
    .calendar .day {
        flex: 0 0 calc(1 / 7 * 100% - 20px);
        padding: 10px;
    }
    .calendar .row .day:not(.-day-7) {
        border-right: grey 1px solid;
    }
    .calendar .row .day {
        height: 60px;
    }
    .control,
    .search {
        display: flex;
        justify-content: center;
    }
    .control a {
        padding: 10px;
        margin: 10px;
    }
    .search * {
        padding: 5px;
        margin: 5px;
        text-align: center;
    }
    .search input {
        background-color: inherit;
        border-top: none;
        border-right: none;
        border-left: none;
    }
    .search input,
    .search button {
        outline: none;
        width: 100px;
    }
</style>
{% endblock %}

{% block content %}
<div class="calendar">
    <div class="title">{{ month_label }} {{ year }}</div>
    <div class="control">
        {% set prev_year = year if month > 1 else year - 1 %}
        {% set prev_month = month - 1 if month > 1 else 12 %}
        {% set next_year = year if month < 12 else year + 1 %}
        {% set next_month = month + 1 if month < 12 else 1 %}
        <a href="{{ url_for('memories.calendar', year=prev_year, month=prev_month) }}">Last Month <-</a>
        <a href="{{ url_for('memories.calendar', year=next_year, month=next_month) }}">-> Next Month</a>
    </div>
    <div class="header">
        <span class="day -day-1">Mon</span>
        <span class="day -day-2">Tue</span>
        <span class="day -day-3">Wed</span>
        <span class="day -day-4">Thu</span>
        <span class="day -day-5">Fri</span>
        <span class="day -day-6">Sat</span>
        <span class="day -day-7">Sun</span>
    </div>
    {% for row in [0, 1, 2, 3, 4, 5] %}
    <div class="row">
        {% for col in [0, 1, 2, 3, 4, 5, 6] %}
        {% if row * 7 + col < month_list | length %}
        {% set day = month_list[row * 7 + col] %}
        {% set has_file = month_file_list[row * 7 + col] %}
        {% if day %}
        <a href="{{ url_for('memories.memory', year=year, month=month, day=day) if day else '#' }}" class="day -day-{{ col + 1 }}">
            {{ day }}{% if has_file %}*{% endif %}
        </a>
        {% else %}
        <span class="day -day-{{ col + 1 }}"></span>
        {% endif %}
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</div>
<form class="search" action="{{ url_for('memories.calendar_go') }}" method="post">
    <span class="title">Search a date: </span>
    <input name="year" type="number" placeholder="year" required />
    <input name="month" type="number" placeholder="month" required />
    <button type="submit" id="go-to-date">Go</button>
</form>
{% endblock %}

templates/memories/day.jinja
{% extends "base.jinja" %}

{% block content %}
<nav>
    <a href="{{ url_for('memories.calendar', year=year, month=month) }}"><- Back to Calendar</a>
</nav>
{% if content %}
<div id="preview">
    {{ content }}
    <a href="{{ url_for('memories.edit', year=year, month=month, day=day) }}">Edit</a>
</div>
{% else %}
<div id="preview">
    <h1>{{ month }}月{{ day }}日</h1>
    <h2>Oops...</h2>
    <p>There's no memory on this day, do you want to create one?</p>
    <a href="{{ url_for('memories.edit', year=year, month=month, day=day) }}">Create Memory</a>
</div>
{% endif %}
{% endblock %}

templates/memories/edit.jinja
{% extends "base.jinja" %}

{% block css %}
<style>
    #edit-memory #content {
        min-height: calc(100% - 40px);
        display: flex;
    }
    form {
        flex: 0 0 calc(50% - 20px);
        display: flex;
        flex-direction: column;
    }
    input[type="submit"] {
        width: 100px;
        padding: 10px;
        margin: 10px auto;
    }
    #markdown {
        flex: 1;
        padding: 0 10px;
        width: 100%;
    }
    #preview {
        flex: 0 0 50%;
        padding-left: 20px;
    }
</style>
{% endblock %}

{% block body_id %}edit-memory{% endblock %}

{% block content %}
<form action="{{ url_for('memories.edit_post', year=year, month=month, day=day) }}" method="post">
    <textarea id="markdown" name="content">{{ raw_content }}</textarea>
    <input type="submit" value="Preview" />
</form>
<form id="preview" action="{{ url_for('memories.save', year=year, month=month, day=day) }}" method="post">
    {{ content }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

{% block additional_js %}
<script type="text/javascript">
    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight)+"px";
    }
    window.onload = function() {
        var textarea = document.getElementById('markdown');
        auto_grow(textarea);
        textarea.onkeyup = auto_grow(textarea);
    };
</script>
{% endblock %}

templates/not-found.jinja
{% extends "base.jinja" %}

{% block content %}
Oops... There is nothing on this page.
{% endblock %}